### ISSUE TITLE
Backup of "smartcontr.actor"

### ISSUE THREAD

**Issue by balistof** [burstdev/old-site#1]
I am contacting you because @ciyam was pointing me to you. I am looking for a backup of "smarcontr.actor". Specifically for the AT generator.

**Comment by ciyam** [comment]
I never had a copy of that website - @vbcs did take one (from what I remember) and @burstdev disappeared. The smart contracts it had a UI for are just the ones that are already published anyway so you don't really need it to create one if that is what you are trying to do.

**Comment by sjlu** [comment]
Closing this and killing issues / pull requests as this is a really really old repo.
